### ISSUE TITLE
missing Ground_Snow_Decal_01.png 

### ISSUE THREAD

**Issue by marangonico** [OpenSceneryX/Library#84]
It seems that the resource "\decals\snow\1\Ground_Snow_Decal_01.png" is missing in the manifest.xml

**Comment by aussig** [comment]
Verified. The new decal library generation code doesn't parse any textures from the file! DOH.

We need to support all valid texture references found in `.dcl` files [as documented](https://developer.x-plane.com/article/standard-shading-options-for-x-plane-10-scenery/#Commands_to_Control_Decals):
```
DECAL <scale> <texture file>
DECAL_RGBA <scale> <texture file>
DECAL_KEYED <scale> <r> <g> <b> <a> <alpha> <texture file>
DECAL_PARAMS <scale> <dither> <r> <g> <b> <a> <m> <k> <r> <g> <b> <a> <m> <k> <texture file>
DECAL_PARAMS_PROJ <scale_x> <scale_y> <dither> <r> <g> <b> <a> <m> <k> <r> <g> <b> <a> <m> <k> <texture file>
```
